# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='FluentComment',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('django_comments.comment',),
        ),
    ]
