# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_assignee_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='families.Group'),
        ),
    ]
