# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20160901_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
