# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 20:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, default='')),
                ('profile_pic', models.ImageField(blank=True, default='', upload_to='')),
                ('sex', models.CharField(blank=True, choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=10)),
                ('phone_num', models.CharField(blank=True, default='', max_length=30)),
                ('twitter', models.URLField(blank=True, default='')),
                ('facebook', models.URLField(blank=True, default='')),
                ('snapchat', models.URLField(blank=True, default='')),
                ('userName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
