# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160811_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
