# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-12 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, default='')),
                ('invite_reason', models.CharField(blank=True, default='', max_length=64)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='festivals.Event')),
                ('group', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='familygroup', to='auth.Group')),
            ],
            options={
                'verbose_name_plural': 'groups',
            },
        ),
    ]
