# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('amount', models.IntegerField(blank=True, default='')),
                ('unit', models.CharField(blank=True, choices=[('g', 'Grams'), ('oz', 'Ounces')], default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('serving_size', models.IntegerField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='', max_length=255)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_group', to='auth.Group')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredient', to='families.Ingredient')),
            ],
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='familygroup', to='auth.Group'),
        ),
    ]
