# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 20:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='familygroup',
            new_name='group',
        ),
    ]
