# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='invite_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
