# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_auto_20160803_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name_plural': 'groups'},
        ),
    ]
