# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_auto_20160901_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_ingredient', to='families.Ingredient'),
        ),
    ]
