# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_auto_20160808_1939'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='FamilyGroup',
        ),
    ]
