# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-01 00:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_auto_20160901_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='meal',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_meal', to='families.Meal'),
        ),
    ]
