# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_auto_20160808_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familygroup',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='festivals.Event'),
        ),
    ]
