# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-10 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0004_auto_20160901_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
    ]
