# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-14 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0007_auto_20160913_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='day',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='meal',
            name='time',
            field=models.CharField(blank=True, choices=[('Breakfast', 'breakfast'), ('Lunch', 'lunch'), ('Dinner', 'dinner')], default='', max_length=255),
        ),
    ]
