# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-21 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0009_vehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_make',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_model',
            field=models.CharField(default='', max_length=255),
        ),
    ]
