# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0010_auto_20160921_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='day',
            new_name='day_choices',
        ),
    ]
