# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 16:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0011_auto_20161011_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='day_choices',
            new_name='day',
        ),
    ]
