# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0013_auto_20161025_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.CharField(blank=True, choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='day',
            name='breakfast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Breakfast', to='families.Meal'),
        ),
        migrations.AddField(
            model_name='day',
            name='dinner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Dinner', to='families.Meal'),
        ),
        migrations.AddField(
            model_name='day',
            name='familygroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Day', to='families.FamilyGroup'),
        ),
        migrations.AddField(
            model_name='day',
            name='lunch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Lunch', to='families.Meal'),
        ),
    ]
