# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0014_auto_20161103_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='FestivalDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.CharField(blank=True, default='', max_length=255)),
                ('date', models.DateTimeField()),
                ('breakfast', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Breakfast', to='families.Meal')),
                ('dinner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Dinner', to='families.Meal')),
                ('familygroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Day', to='families.FamilyGroup')),
                ('lunch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Lunch', to='families.Meal')),
            ],
        ),
        migrations.RemoveField(
            model_name='day',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='day',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='day',
            name='familygroup',
        ),
        migrations.RemoveField(
            model_name='day',
            name='lunch',
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
