# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-16 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0017_post_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_by',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='post',
            field=models.TextField(default=''),
        ),
    ]
