# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-14 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0018_auto_20170116_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='recipe_url',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
    ]
