# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-28 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0020_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='expires_at',
            field=models.DateTimeField(blank=True, default=''),
        ),
    ]
