# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-28 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0021_auto_20171028_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitations',
            name='expires_at',
        ),
        migrations.AlterField(
            model_name='invitations',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
