# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-28 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0022_auto_20171028_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitations',
            name='invitationid',
        ),
    ]
