# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-28 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0023_remove_invitations_invitationid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitations',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255),
        ),
    ]
