# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-27 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day_choices',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
