# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_event_cover_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cover_photo',
            field=models.ImageField(blank=True, default='', upload_to='media/'),
        ),
    ]
