# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-11 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0002_event_day_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day_choices',
        ),
    ]
