# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-13 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0003_remove_event_day_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='alcohol_policy',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='android_app',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='camping_stove',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='hydration_pack',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='instagram',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='ios_app',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='parking_pass',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='totems',
            field=models.BooleanField(default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='venue_map',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='youtube',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='registration_site',
            field=models.URLField(blank=True, default=''),
        ),
    ]
