# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0004_auto_20161013_1148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restrictions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totems', models.BooleanField(default='')),
                ('hydration_pack', models.BooleanField(default='')),
                ('camping_stove', models.BooleanField(default='')),
                ('beer', models.BooleanField(default='')),
                ('wine', models.BooleanField(default='')),
                ('liqour', models.BooleanField(default='')),
                ('alcohol_policy', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='alcohol_policy',
        ),
        migrations.RemoveField(
            model_name='event',
            name='camping_stove',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hydration_pack',
        ),
        migrations.RemoveField(
            model_name='event',
            name='totems',
        ),
        migrations.AddField(
            model_name='restrictions',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_restrictions', to='festivals.Event'),
        ),
    ]
