# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 17:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0006_event_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restrictions',
            old_name='liqour',
            new_name='liquor',
        ),
    ]
