# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 19:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0007_auto_20161015_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(null=True)),
                ('street', models.CharField(default='', max_length=255)),
                ('state', localflavor.us.models.USStateField(default='')),
                ('zipcode', localflavor.us.models.USZipCodeField(default='')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='event_address', to='festivals.Event')),
            ],
        ),
    ]
