# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0009_event_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='website',
        ),
    ]
