# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0010_remove_event_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='number',
            new_name='street_number',
        ),
    ]
