# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 19:48
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0011_auto_20161015_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='phone',
            field=localflavor.us.models.PhoneNumberField(default=''),
        ),
    ]
