# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-15 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('festivals', '0012_event_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='', max_length=255),
        ),
    ]
